apiVersion: v1
kind: Service
metadata:
  name: {{ include "emailservice.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "emailservice.name" . }}
    helm.sh/chart: {{ include "emailservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: {{ .Values.service.port }}
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "emailservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
